Disable DM-Verity and enable persistent /data in facdev build flavor (#564)
* Fixup rotten mount-data script.
* Disable DM verity for facdev build flavor.
* Mount persistent /data in facdev builds.

diff --git a/poky/meta-qti-bsp/recipes-core/systemd/systemd/mount-data b/poky/meta-qti-bsp/recipes-core/systemd/systemd/mount-data
--- a/poky/meta-qti-bsp/recipes-core/systemd/systemd/mount-data
+++ b/poky/meta-qti-bsp/recipes-core/systemd/systemd/mount-data
@@ -53,28 +53,46 @@ make_userdata() {
 }
 
 
+make_tomlog() {
+  if ! test -f $TOM_LOG; then
+    ls -la /factory/cloud >> $TOM_LOG
+    echo "QSN=`cat /sys/devices/soc0/serial_number` # ESN=`emr-cat e`" >> $TOM_LOG
+  fi
+  sync
+}
+
 case "$1" in
   start )
-    if grep $UNBRICK_KEY /proc/cmdline > /dev/null; then
-      echo "Mount-data in UNBRICK MODE" > /dev/kmsg
-      mount -o size=64M -t tmpfs none /data/
-      make_userdata false
-    else
-      if ! mount /data; then
+    mount /data
+    mounted=$?
+    if [ $mounted -ne 0 ]; then
         make_userdata true
+    else
+        make_userdata false
+    fi
+    PACKOUT_FLAG=`/bin/emr-cat o`
+    if [ $? -eq 0 ]; then # If we can't test the packout flag we don't want to risk remounting
+      if [ $PACKOUT_FLAG -eq 00000000 ]; then # If packout flag is not set
+        echo "Not packed out, remounting /factory rw" > /dev/kmsg
         sync
+        mount -o remount,rw /factory
+        make_tomlog
       fi
+    else
+      echo "Couldn't determine packout status" > /dev/kmsg
     fi
     ;;
 
   stop )
     echo "Unmounting /data"
-    sync
     umount /data
     if test -e $WIPE_COOKIE; then
       blkdiscard -s /dev/block/bootdevice/by-name/userdata
       blkdiscard -s /dev/block/bootdevice/by-name/switchboard
+      bootctl f set_unbootable a
+      bootctl f set_unbootable b
     fi
+    sync
     ;;
 
   * )
